### ISSUE TITLE
Project : Monitoring & Slow log

### ISSUE THREAD

**Issue by panupong-puttarathamrongkul-dev** [panupong-puttarathamrongkul-dev/unname#14]
**Customer/Developer Scenario**
As a ..., I 

**Describe the solution you'd like**
- https://github.com/korfuri/django-prometheus/
- https://www.datadoghq.com/blog/monitoring-django-performance/
- https://sentry.io/pricing/
- https://www.morethanseven.net/2011/06/09/Logging-django-performance/
- https://dogslow.readthedocs.io/en/stable/
- https://github.com/jazzband/django-silk
- http://invitebox.github.io/django-live-profiler/ https://github.com/InviteBox/django-live-profiler
- https://stackoverflow.com/questions/17108810/django-log-filter-for-slow-sql-queries
- https://stackoverflow.com/questions/17970611/django-query-extremely-slow
- https://docs.djangoproject.com/en/dev/topics/logging/#configuring-logging
- https://stackoverflow.com/questions/4375784/log-all-sql-queries
- https://stackoverflow.com/questions/42122815/how-to-configure-django-logging-for-production-under-gunicorn-server
- https://www.agiliq.com/blog/2017/12/configure-django-log-exceptions-production/
- https://lincolnloop.com/blog/django-logging-right-way/
- https://www.reddit.com/r/django/comments/6wxcsp/django_logging_in_production/
- https://medium.com/@24est.bnpp/%E0%B8%A1%E0%B8%B2%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87-real-time-event-logging-%E0%B9%81%E0%B8%9A%E0%B8%9A%E0%B8%87%E0%B9%88%E0%B8%B2%E0%B8%A2%E0%B9%86-%E0%B9%83%E0%B8%99-3-steps-%E0%B8%94%E0%B9%89%E0%B8%A7%E0%B8%A2-sentry-%E0%B8%81%E0%B8%B1%E0%B8%99%E0%B9%80%E0%B8%96%E0%B8%AD%E0%B8%B0-13a157e22816

**Expectation / Requirement Acceptance**
-

**Additional context**
-

**Comment by panupong-dev** [comment]
https://stackoverflow.com/questions/37543342/user-access-logging-in-django

**Comment by panupong-dev** [comment]
https://docs.sentry.io/clients/python/integrations/#integration-with-logging
